### ISSUE TITLE
Pulse update and scroll position should be locked to col 0

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#15]
The pulse update calculation should be ideally locked to before updating column 0.  It probably won't cause an issue but it just bugs me.

Scroll should be locked to column 0 update to avoid shearing, but it might cause other issues depending upon timing.  Suck it and see?

**Comment by gbevin** [comment]
There's no shearing, the LEDs are updated in a double buffer for those refreshes that take a while to complete. The buffer swap only happens when the whole frame is calculated.
