### ISSUE TITLE
repeated use of cell macros for lookup wastes loads - optimisation suggestion

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#16]
This sort of pattern is common in the touch handling code in ls_touchInfo.ino, ls_handleTouches.ino and possibly other places:

     cell(col, row).touched = untouchedCell;
      cell(col, row).lastTouch = 0;
      cell(col, row).clearSensorData();
      cell(col, row).vcount = 0;
      cell(col, row).velocity = 0;

cell is a macro, looking up a value in a doubly nested array:

#define sensorCell()               touchInfo[sensorCol][sensorRow]
#define cell(col, row)             touchInfo[col][row]

Each of these involves 3 loads - get the value of touchInfo, the contents of the columns, and then the contents of the row.  Looking at the spec sheet for the Arduino Due (AT91SAM3X8E?) I find no mention of caches beyond a note that they aren't usually used.

Each of these loads is going to cost anywhere from 5 (guess, with L1 cache which may not be present) to 100s of cycles.  And the answer is always going to be the same (if I understand correctly - you don't create new cells and replace existing cells) : the inner pointer to the cell structure.

The repeated accesses can't be optimised away because the compiler can't prove that a write to (say) thing.touched isn't a write into the array structure or the touchinfo pointer itself.  

However, you can give the compiler the information it needs:  An easy optimisation here would replace this sequence with

      currentCell = cell(col,row)
      currentCell.touched = untouchedCell;
      currentCell.lastTouch = 0;
      currentCell.clearSensorData();
      currentCell.vcount = 0;
      currentCell.velocity = 0;

etc.

Hope this is useful.

**Comment by alexbbrown** [comment]
It can't be optimised away because it can't prove that a write to (say) touched isn't a write into the array structure or the touchinfo pointer itself.

**Comment by gbevin** [comment]
Thanks for the suggestion, it's indeed a nice optimization opportunity that slipped through the cracks :-)

The repeated locations are infrequently used, so I doubt the impact would be noticeable though, but I'll see if it does.

**Comment by gbevin** [comment]
It makes me think of one optimization I now remember I wanted to perform, but forgot when working on other things. Ie. sensorCell() can be pre-evaluated at each loop iteration as currentSensorCell, and not require any lookups anywhere during that loop afterwards.

**Comment by gbevin** [comment]
Now I remember why the optimization wasn't done, doing this: currentCell = cell(col,row) will copy the TouchInfo structure values, which is hugely expensive. So the only option is taking the address of the array element and storing it into a pointer. That by itself is quite an expensive operation and only makes sense if there's really a lot of use for that particular instance, for instance in the case of sensorCell(). For instance, merely taking the instance address and storing it into a pointer for each loop iteration of the sensor scan, adds 182 microseconds to the full surface scan. Thankfully sensorCell() is very widely used, which makes this pre-lookup gain 319 microseconds overall, yielding an overall improvement of 137 microseconds. Not much, but sufficient to put this in place. I don't think it makes sense to do this elsewhere though.

**Comment by alexbbrown** [comment]
good point on the struct thing; not clear on the semantics of this language - is it c or merely c-like? taking the address of the array element and storing it into a register  is what the compiler is doing in that operation, and should be cheap apart from the fact that a register or stack element is used.  pointer writes should be cheap enough - I clearly have some learning to do.

Can you add some context to those numbers? is it 319 microseconds per second of operation? or per benchmark which takes 5 minutes?  

Thanks

**Comment by gbevin** [comment]
319 microseconds per full surface scan, i.e. about 200 operations. So it's a bit more than 1 microsecond per operation.

**Comment by gbevin** [comment]
It's C with C++ extensions

**Comment by alexbbrown** [comment]
what's the total cost currently? you mentioned 4ms before, so 137 is 3%.  I'd pay good money for 3% in my project.

**Comment by gbevin** [comment]
Going from 4280 to 4143.

**Comment by alexbbrown** [comment]
Ok now i'm curious : if one store and the associated loads elsewhere costs 182ms, which is 4%, that suggests that elimination of other stores might be worthwhile.  If it's the additional loads, then passing the cell around as a register argument may get rid of that cost.

**Comment by alexbbrown** [comment]
or is it possible that its accidentally doing a struct copy that you pointed out was so problematic?

**Comment by alexbbrown** [comment]
did you measure the store by adding the store alone and leaving the read macros in place?

**Comment by alexbbrown** [comment]
how many CPU cycles is 182ms?  I don't know the clock speed (80Mhz?) or the IPC of this processor.

**Comment by gbevin** [comment]
I explicitly took the address, so it's not copying the struct. Yes, I measured by just doing the store and leaving the read macros in place. Second timing, removing the read macros and replacing them with the pointer deference to the previous lookup.

**Comment by gbevin** [comment]
84MHz

**Comment by gbevin** [comment]
it's not ms, it's µs (microseconds)

**Comment by alexbbrown** [comment]
what's the % level of noise on these performance measurements?  

xperhaps grab the gain we got, but 15000 cycles for one store.  seems excessive to me.

**Comment by gbevin** [comment]
No noise, it's a real-time system, all the measurements are deterministic and 100% reproducible.

**Comment by alexbbrown** [comment]
and the control timing was done just before the store test one, cold boot and everything?  Could you kick off another control run please?

**Comment by gbevin** [comment]
I know how to measure this :-)

**Comment by alexbbrown** [comment]
I have no doubt, it's just I can't measure mine; it's under the xmas tree :)

**Comment by gbevin** [comment]
These timings are correct, and yes it with cold reboot, multiple samples, repeated scenarios, etc etc

**Comment by alexbbrown** [comment]
oh, when I get the build environment running, do you have a performance test harness  (or technique) you can share?

**Comment by gbevin** [comment]
Not really, there's no test harness short of some of the built-in test and debug methods that are in the code. There are no automated tests for features or functionalties.

**Comment by alexbbrown** [comment]
Could you share your timing procedure if you don't mind?  It sounds like a fun thing to do.

the number 15000 is interesting though - whether we consider it the cycle count for the gain or for the cost of the store, it's the right sort of scale for a full scan.  15000 / 25 / 8 is 75.

**Comment by gbevin** [comment]
Compile the code with DEBUG_ENABLED (ls_debug.h).
Set the LinnStrument to serial mode (Update OS Global option).
Connect the Arduino serial monitor and start it.
Activate the secret switch in column 17 row 5 that prints out the timing of each full surface scan over serial.
Watch it run.

**Comment by gbevin** [comment]
I gotta go now though

**Comment by alexbbrown** [comment]
sure, thanks for taking the time to hand hold me.
