### ISSUE TITLE
ls_touchinfo.ino uses divides

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#17]
divides on small devices are known to be violently expensive.  may be worth investigating lookup tables since your divisor is often constant.

note that http://www.hackersdelight.org/divcMore.pdf has an algorithm for an integer divide by 5 that's very very small.

**Comment by gbevin** [comment]
I measured the impact of the divides when writing them, in these situations the impact is neglectable and not worth the added complexity of going for an alternative solution.
