### ISSUE TITLE
Optimised LED color bitmap representation like mga modeX

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#18]
In case LED writing cost is an issue, this suggestion reduces the cost of the LED write (but not the actual SPI write, which may be reduced by DMA offloading?)

Currently data is stored as 

leds[visibleLeds][LED_LAYER_COMBINED][actualCol][rowCount]

buffer|visible / layer / column / row / RGBcolour

most of the calculations in refreshLedColumn can be removed by:

1) restructuring to store a per column per colour bitmap in the leaf

buffer | visible / layer / column / color / row

gets rid of the shifts, masks, removes the inner loop.

obviously the colour accessors now need to do the colour conversion from enumerated colour to RGB colour, and shift their row position and do set/clear semantics instead of writes.  However, there are probably fewer indexed colour writes (and indexed reads) than updates.

blit reads and writes (startBufferedLeds) - such as during copying layers becomes 2x as cheap (there are 4 bits in a colour name, and 8 bits in a row)

This change so far fails to handle layer masking (where color_off allows a cell to show through).  for that an alpha channel is required.  

Now we have 4 channels, and this can even be extra optimised by by packing R+G and B+A into 16-bit pairs, reducing copy cost by 33%.  If there are plans to extend the bit depths to 2 bits per channel that might be a mistake.

The layer mask search is no longer done per column for all colours by row, but per column for all rows by color, and the mask bitmap is extracted, unioned with the existing one and masked with the (next) input layer before combination.  All layers must now be visited.

However, there is now an option for a setLedColumn method, in which all 8 cells are set, which may be cheaper for some write operations such as promo/font drawing.

---

Note: if you don't do this, a smaller mod is to 

2) don't do the multi level lookup on each iteration - move the dereference of 

leds[visibleLeds][LED_LAYER_COMBINED][actualCol]

outside the inner loop.

**Comment by gbevin** [comment]
These suggested changes are neglectable, the time is almost all spent in the SPI transfer.
