### ISSUE TITLE
phantom detection fails to detect 4th corner releases - proposed replacement for phantom algorithm

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#19]
While phantom detection correctly discards over threshold phantom touches on the 4th corner, it fails to detect 4th corner releases.

1) choose any 4 corners of a square and press them.
2) three will light up
3) release a lit one.
4) it does not unlight

This is a consequence of the phantom logic - the real (not phantom) 4th press keeps the 3rd over threshold.

----

Here follows a proposal for how to develop an algorithm to allow correct 4th corner detection.  In short, for a suspected 4th corner, re-scale Z by subtracting 50% the average of the 3 stronger corners, and then doubling the remaining load before applying threshold and calculating actual Z.  It's probably a bit more complex than that though.

Looking at the output from secret switch 3, it's clear that there is a significant signal from the 4th button, but the unpressed baseline and scale are modified compared to the first, second and third presses.

In other words, the signal exists to detect the 4th corner correctly, given an appropriate algorithm.

For example, with a Z reading of 1400 on the pressed 3 corners in a 4x3 square, the unpressed corner reads 700.  this is above threshold itself, but when the 4th corner is pressed, all 4 values leap to reach a value slightly larger than 1400.

Once a square has been formed, all 4 affect the others, so it's probably not necessary to track *which* one is the 4th.

If I could find a set standard weights in the pressure ranges appropriate, a linear model could be applied to the sensor readings to re-create the unbiased physical values from the measured ones.  The unpressed bias seems to be somewhere in the region of 30% and 50% of the pressed neighbours.

The bias changes with location over the grid; this is probably due to physical distance between the corners, but there may be an effect from absolute location on the grid.  The effect is relatively small compared to the main effect, so it may be possible to derive an improved algorithm while ignoring this factor.

Suggestions for a standardised mechanism for applying Z to cells would be appreciated.

**Comment by alexbbrown** [comment]
finger in the air, the runtime cost of this extra evaluation should be comparable to the current cost of phantom tracking, which it would entirely replace.

**Comment by gbevin** [comment]
First of all, did you properly calibrate your LinnStrument before digging into the phantom detection logic? If you just upload a custom firmware yourself, the calibration will be gone.

**Comment by alexbbrown** [comment]
This leaves open the question of how to handle larger sets of intersections, but since they are already incorrectly handled, I think this is moot.

 ( I can create phantoms with 5 fingers in the position 1,2,4,8,9 of a 3x3 square )

**Comment by alexbbrown** [comment]
@Geert <<First of all, did you properly calibrate your LinnStrument before digging into the phantom detection logic? >>

Thanks; good point that needed clarifying.  The issues detected are easy to demonstrate in a calibrated linnstrument, in debug mode with a custom firmware (only modifications were those I needed to compile in Arduino IDE).

**Comment by alexbbrown** [comment]
I'm using 1.6.7 with the 1.6.4 SAM board installed.  All uses of char * should pretty much be const char *.

I also get build errors because selectSensorCell is not declared in a header.

I also get link errors because the arduino IDE tries to compile and link the contents of arduino_fixes and library.  moving them aside (after placing them in the appropriate places in the build system) addresses this.

**Comment by gbevin** [comment]
This seems to be fixed with the latest changes.
