### ISSUE TITLE
Phantom detection check for hasNote problematic for some note pairs

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#23]
I have found many (three finger)  case where the selection of a note from two choices gets it wrong.

This effect very rarely shows up in musical use of the device, and certainly is tiny compared to the number of bum notes I play. 

For example, press the first two cells on the top row (1,7 & 2,7), and the bottom left cell (1,0)

the adjacent cell (column 2 row 0) lights most of the time (can depend on finger position in 1,0).

This happens because 2,0, the phantom grabs the 'note' and 'wins' against its phantom-partner because *it gets evaluated first*, which means:
* it can't 'see' the competing press on the phantom-partner (the actual press), so doesn't check it
* the rawZ value of the phantom-partner may not yet be available, so even if that was the decider it might still win
* once it decides it's not a phantom (but it really is) then its touch and its note become visible to the real press which is evaluated shortly afterwards, and the real press loses.

So is a phantom getting evaluated first likely?  Unfortunately yes; and the likelihood varies from rare to very common depending upon the pair of notes in question:

The current scan order (assuming scans operate continuously) means that an button press creating signals on 1,0 and 2,0 (phantom) falling at a random time will be evaluated for 0,2 first 80%+ of the time.

So 2,0 gets it, and effectively blocks 1,0 from getting it, even though the signal is stronger.

similarly, but in reverse, 10,0 steals from 11,0 (with two other suitable touches) and 1,1 steals from 1,6 (ditto)

----

The solution must be able to evaluate BOTH notes new rawz values before the note becomes audible.
Effectively this means deferring the midi send, although a creative solution might do a very very quick pitch bend.

One way to defer midi messages them would be to stick them in a queue from which they could be pulled back out.  

Another would be to wait for all rawz values to be available before starting to handle the touches this implies, then detect all possible touches, and do phantom resolution on this map, and only then send midi.  This would require a scan timing that allowed a full scan to have a small duty cycle, to avoid the presses arriving in the scan itself.

Another would be to do a directed scan for phantoms with refresh - possible touches with 2 partners should get *new* rawz values of the implied fourth corners before claiming the touch.

----

**Comment by alexbbrown** [comment]
I mention the current scan order not because it's bad, but because if scanning was done strictly from left to right, then left corners would always beat right corners, and it would be obvious.  However, that's not how it works, so it isn't so obvious - simply moving the rectangle across the board varies the likelihood of a miss.

**Comment by alexbbrown** [comment]
BTW my theory about the scan timing causing this issue is wobbly; If it were as true as I make out above, then a completely reliable rectangle with 3 touches could be made unreliable by switching the lost touch with its phantom partner.  This isn't the case (although unreliable ones can be made reliable using this technique).

**Comment by alexbbrown** [comment]
Possible solutions:

First option would be to use 'rowsInColsTouched' and 'colsInRowsTouched' to represent phantom touches too - this would allow pre-touched cells (which might be phantoms) to be evaluated in the phantom detection code.

This is my current favourite.
---
Second option is to defer sending touches to the midi layer until such time as a full scan is completed.  The comments sort of imply this happens:

  // check if after a new velocity calculation, this cell is not a phantom touch
  // we piggy-back off of the velocity calculation delay to ensure that we have at
  // least one full scan of the surface before making comparisons against other cells

But this would seem to fail because although a full scan happens before velocity concludes, the rowsInColsTouched and colsInRowsTouched are updated too late for hasNote to take it into account.

**Comment by alexbbrown** [comment]
I think have located the cause of this, but my attempted fix (calcVelocity return true the call 'after' it completes) causes other problems.

in `ls_handletouches.ino`, this comment appears in `handleXYZupdate`:

````
  // check if after a new velocity calculation, this cell is not a phantom touch
  // we piggy-back off of the velocity calculation delay to ensure that we have at
  // least one full scan of the surface before making comparisons against other cells
````

However, the velocity calculation does not have a delay in the current implementation - the shortcircuit logic causes the velocity to be calculated after first touch, without visiting any other cells, and proceeds directly to setting a note.  This effectively causes the phantom cell to become the real cell, since it didn't wait to see if the other cell got a higher reading.

**Comment by gbevin** [comment]
You're right, this comment in a remnant from previous times.
Most phantom presses are now removed through the hasImpossibleX call, the four corner detection is something I left in for the few ones that are still caught in uncalibrated devices.
However, I don't really want to wait for a full scan again since it will introduce an additional delay of at least 4ms, which is too much.

**Comment by gbevin** [comment]
Pushed a fix for this. I actually didn't make sense the leave the old routines in place when the device is calibrated since it could cause the detection of false positives. I also tweaked the range a bit that considers an X to be valid or not. In my testing, this get rid of the wrong detection for those note pairs you  mention.
