### ISSUE TITLE
Cannot bend a note past a minor second

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#24]
If a minor second is held in the most natural way, with two adjacent semitones on the same row, then a note started anywhere but on that row can be pitch bent and have the pitch bent note stop, and a new note starts (and bends) once the columns of the minor second are passed.

This is an unexpected result that may be caused by the phantom algorithm overriding the transfer algorithm.

**Comment by gbevin** [comment]
Can you review this again with the latest changes, I can't seem to reproduce this.

**Comment by alexbbrown** [comment]
I'm going to live on your update and see what happens over a couple days, thanks.

**Comment by alexbbrown** [comment]
Well with a quick check on the latest head I cannot reproduce this; thanks!

**Comment by gbevin** [comment]
Cool! :-)
