### ISSUE TITLE
Macro substitution may cause velocity sxy to be calculated as N + SXY - SY * VY instead of (N + 1) * SXY - SY * VY

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#26]
This issue may affect the range and shape of velocities delivered and their variance as the inter-measurement period changes due to handling serial IO.  Clearly the current algorithm delivers a finely tuned velocity curve and user experience.  It is not based upon measurement of the performance of the device, but on code inspection.

However, my guess is that the proposed fix below may deliver two advantages, after curve calibration: 1) different, perhaps wider range of positive physical velocity values appear in the positive sxy velocity range.  2) less susceptibility of the velocity calculating to timing changes between velocity measurements (not that I have detected any).

In d0a034a, the VELOCITY_N macro was introduced.  It now exists as 

 #define VELOCITY_N             VELOCITY_SAMPLES + VELOCITY_ZERO_POINTS

It's used in two places:

ls_touchInfo.ino:const int VELOCITY_SXX = (VELOCITY_N * VELOCITY_SUMXSQ) - VELOCITY_SUMX * VELOCITY_SUMX;
ls_touchInfo.ino:      int sxy = (VELOCITY_N * sensorCell->velSumXY) - VELOCITY_SUMX * sensorCell->velSumY;

According to my local instance of cpp, building C (I assume this is the same rules as the arduino compiler) this will be expanded to 

ls_touchInfo.ino:      int sxy = (VELOCITY_SAMPLES + VELOCITY_ZERO_POINTS * sensorCell->velSumXY) - VELOCITY_SUMX * sensorCell->velSumY;

But before d0a034a, this would have been calculated as 

ls_touchInfo.ino:      int sxy = (VELOCITY_SAMPLES * sensorCell->velSumXY) - VELOCITY_SUMX * sensorCell->velSumY;

Which means the scaling of sensorCell->velSumXY is lost - they are now unscaled:

N + SXY - SY * VY instead of (N + 1) * SXY - SY * VY

instead of 

(N + 1) * SXY - SY * VY

I don't have my stats book to hand, and don't recall enough stats to know this one by heart, but this seems unlikely to me.

---

Note that this code change has been in for a long time, and the curves are likely to be calibrated to the algorithm as it stands today.  Simply replacing the algorithm with 

 #define VELOCITY_N             (VELOCITY_SAMPLES + VELOCITY_ZERO_POINTS)

Seems to work fine but may have an impact on parameters of the note governed by velocity.

It will very likely not operate with the same finely tuned response as the current version of the software unless the curves are adjusted to recognise the new values.  Even if it is able to detect lower velocity values (my guess), It will not deliver an enhanced range of output note velocities unless the curves are adjusted.  Stability vs timing changes will occur as a consequence of the change.

**Comment by gbevin** [comment]
This is a great find, thanks. The error most certainly stems from me having done Java for so long where there are no macros. When I added that macros, I'm very certain that I thought of it as a const instead. I'll test the change, but it could explain why at one point I had trouble finding stable lower velocity values.

**Comment by alexbbrown** [comment]
Deferring to your expertise having built the curves, I'd like to suggest that where the current curves are tuned for the existing algorithm, it may be possible to extract equivalent curves for all but low velocities for the revised sum square equation mathematically by injecting a standard time delta into both equations and calculating the curve value required to yield the same velocity value for the same time value (for each pressure level).

Hopefully if this change stabilizes velocity in the presence of high io load (long inter measurement period) then the resulting curve would then apply in the presence of varying load.

Once again, I have only encountered good results interacting with the device, and have not encountered any unexpected soft or loud notes in use.

I am interested in increased timing resilience to enable modifications for my own use that further load the main loop without breaking response characteristics.

**Comment by gbevin** [comment]
Interestingly this puts a lot of other things in an interesting perspective at hindsight, the VELOCITY_SUMX and VELOCITY_SUMXSQ macros are wrong too. They should be:

#define VELOCITY_N             (VELOCITY_SAMPLES + VELOCITY_ZERO_POINTS)
#define VELOCITY_SUMX          6    // x1 + x2 + x3 + ... + xn
#define VELOCITY_SUMXSQ        14   // x1^2 + x2^2 + x3^2 + ... + xn^2

I was rushing like crazy to get these velocity improvements in before NAMM last year, while traveling to Estonia and preparing for a keynote talk and musical performance. Many late night and lots of trial and error. It paid off by having a super playing instrument at NAMM, but the velocity never has been as stable as I thought it would have been.

**Comment by alexbbrown** [comment]
One concern I have with my suggested change is that the velocity calculation may now be much more sensitive to systematic errors in time capture, specifically the 4ms quantization of the output of micros().

Back of the envelope calculation says that velocity is calculated from the pressure change over around 40us.  (4000/201)*2.

I need to check the code to get the time delta but if it uses micros then the likely computed values for a real time delta of 40us are quantized to 32,36, 40 and 44, 48 for zero one or two quantization misses, which could manifest as velocity error of -20 to +20%.

This may well be a musically acceptable range, I have no experience.

So two questions:

1) Roughly how long is the shortest period in which you can measure velocity before deceleration hits in for good players in your experience-is it the same order of magnitude as 40us or way longer or shorter?

2) what was your motivation for the current clustering of velocity measurements for a single cell on first touch, rather than interleaved with other cells or just measure again once at the next scan?  Is it to get a stable result, to get an immediate result, to avoid a 4ms delay in midi note dispatch or something else?

I ask because I am contemplating what would happen if I varied this strategy in my experiments.

**Comment by gbevin** [comment]
1) no real measurements on this, purely based on testing and feeling, experimenting with other players to get their thoughts on different variations on the curves and tweaks
2) we need the initial slope of the acceleration over at least three samples, waiting for three round-trips is too long to get the actual initial acceleration and be able to calculate the slope. Hence the clustering and rapid re-reads of the same cell during velocity calculation

**Comment by alexbbrown** [comment]
Thanks Geert, that really helps me.

By increasing the measurement duration to just 160us the possible quantization error is reduced to 5%, which is certainly better I expect I can control the velocity of my fingers.

Sounds like that wouldn't be too bad of a number.  I am looking for scientific studies but haven't found one with timings in yet.

**Comment by gbevin** [comment]
I pushed a commit with this in mind and reworked the code that is dependent on it. The curve are most certainly not the final ones though, haven't had time to compare with the previous feel yet. We did mean to rework the velocity behavior though to give a stronger accent to the upper-mid section, since that seems to be what most musicians expect.
