### ISSUE TITLE
Sensor settling time based on column touches always checks column 0

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#27]
Presumably the sensor settling time logic works fine as is, but there's a curious pattern in 

ls_sensor.ino

Where comments do not seem to match my understanding of the code:

The comments suggest that the presence of absence of touches in the column should gate (and change) a settling time and re-read of the sensor.  However, it always checks column 0, not the current sensor column.

```
    // if there are active touches in the column, always use a settling time
    if (sensorCol == 0) {
      delayUsec(READZ_DELAY_SWITCH);
    }
    else if (rowsInColsTouched[0]) {
      delayUsec(READZ_DELAY_SENSOR);
    }
```

The main effect is that if rawZ <= READZ_SETTLING_PRESSURE_THRESHOLD it will never settle at all for sensors (unless a switch in column 0 is currently touched).

```
    // if there are no active touches in the column, but the raw pressure without settling time exceeds the value threshold,
    // introduce a settling time to read the proper stabilized value
    if (rowsInColsTouched[0] == 0 && rawZ > READZ_SETTLING_PRESSURE_THRESHOLD) {
        delayUsec(READZ_DELAY_SENSORINITIAL);
        rawZ = 4095 - spiAnalogRead();
    }
```

Perhaps this should read: `rowsInColsTouched[sensorCol]`?

**Comment by gbevin** [comment]
Thanks for finding this, fixed in latest commit
