### ISSUE TITLE
percentRawZ delay calculation may effectively be on-off (not linear) 

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#28]
In readX and readY, the following logic appears:

````
    d = READY_MAX_DELAY - (READY_RANGE_DELAY * min(zPct - READY_FLATZONE, READY_RANGE) / READY_RANGE);
````

but since all the values in this statement are integers, then it evaluates to the same as

    d = READY_MAX_DELAY - (READY_RANGE_DELAY * (zPct - READY_FLATZONE < READY_RANGE) ? 0 : 1);

Was this intended to vary the delay linearly?  if so then something like:

````
    d = READY_MAX_DELAY - (float(READY_RANGE_DELAY) * float(min(zPct - READY_FLATZONE, READY_RANGE)) / float(READY_RANGE));
````

May work better, if my understanding of precedence of *, / is correct, and if min is polymorphic or generic.

**Comment by gbevin** [comment]
I'll have to take some time to think this through, very tired atm. In any case, float can't be used, it's way too slow on this processor.

**Comment by gbevin** [comment]
Hmmm, afaik * and / have the same precedence and are evaluated from left to right in the absence of parenthesis. So this first does the multiplication, then the division. This should give enough resolution to get the results that are intended without going through decimal numbers.

**Comment by alexbbrown** [comment]
I'm pretty sure you are correct here, sorry for the noise.
