### ISSUE TITLE
043a9d7 "Improvements to Phantom" ... my device unresponsive to touch before calibration [with fix]

### ISSUE THREAD

**Issue by alexbbrown** [rogerlinndesign/linnstrument-firmware#29]
Easily rectified by going back to previous master, or undoing changes to ls_handletouches.

The issue seems to be that isPhantomTouch no longer has a return at the end, so the return value is simply noise (whatever was last in the return register).  

Suggested fix: add return false at the end of isPhantomTouch.

**Comment by gbevin** [comment]
Fixed
