### ISSUE TITLE
SAM Board version: 1.6.11 or 1.6.4?

### ISSUE THREAD

**Issue by WetzelVictor** [rogerlinndesign/linnstrument-firmware#37]
On the RogerLinn website (http://www.rogerlinndesign.com/ls-source-code.html), firmware update instructions indicates that v1.4 of Samboard Cortex ARM M3 is recquired. Yet in the read-me of this Github, v1.6.11 is recquired.
Is it really important? Which one should we choose?

**Comment by gbevin** [comment]
It is important, the README has the right information.
