### ISSUE TITLE
Linnstrument128 Sequencer has only 8 steps

### ISSUE THREAD

**Issue by metakeule** [rogerlinndesign/linnstrument-firmware#38]
Thanks for making this great product!

According to the documentation at
http://www.rogerlinndesign.com/ls-sequencer.html

It should be possible to edit up to 32 steps on the Linnstrument128
via the page buttons. However, only the first column of the page buttons
seems to be functional.

8 steps are somewhat limiting for real sequencing...

**Comment by gitouttahea** [comment]
HI metakeule,

Sorry— it’s a little confusing, and I also just noticed a small error on that page, which I have just corrected. Here’s the answer:

The 8 Page Select buttons are only visible if no note is selected. If a note is selected, the lower-right area is used to display the selected note’s data. To deselect a note and therefore view the 8 Page Select buttons, either press any button in the Step Select Bar or press anywhere in columns 9 or 10.

This is explained on that page under the heading "Sequencer Controls (LinnStrument 128)". 

Roger Linn

**Comment by metakeule** [comment]
Hi Roger,

I guess my wording was not clear...

The problem was not to "find" the page select buttons as they appear just fine as described.
The problem is that when I press them, I am not able to set notes past the 8th step (so the sequencer is only functional for 8 steps).

Thank you!

**Comment by gitouttahea** [comment]
Hi meta,

I think I understand now. You must change the Sequence End from default of Step 8 to your desired ending step. This is done by holding Switch1 while pressing the desired ending step in the Step Select Bar. 

For future support, could you please email me at support@rogerlinndesign.com <mailto:support@rogerlinndesign.com> or use the LinnStrument forum? I’d prefer not to use Github for support questions. 

Also, can you tell me your name (and your forum handle) so I can associate them with your Github handle in my records? 

Thanks,
Roger Linn

**Comment by metakeule** [comment]
Hi Roger,

thanks for your patience!

I missed the part with the sequence end in the manual although I read it several times. Strange... Maybe the mix of Linnstrument128 and the larger Linnstrument features (while being compact) is too distracting from the reading and one fully separate and complete pages for each variant would be more clearly.

If I will need more help, I will contact you via email.

Sorry, I don't like the kvraudio forums since they are full of ads (and its based on an old php-based forum that looks very insecure to me -> I expect malware when visiting the site).  

However your support has been great and you are clearly serious about your products and your customers. Keep on the good work!

Thanks and cheers!
