### ISSUE TITLE
Feature request: MIDI media converter

### ISSUE THREAD

**Issue by hippi-viking** [rogerlinndesign/linnstrument-firmware#52]
Not sure if using only either the USB or the DIN ports for MIDI is a hardware or software limitation. If it is the latter, could a special MIDI passthrough mode be viable forwarding messages between the USB and DIN ports? (This way the Linnstrument would also work as a MIDI media converter simplifying a few smaller setups.)

**Comment by gbevin** [comment]
Sadly this is not possible due to hardware restrictions.
