### ISSUE TITLE
License contradiction (CC-BY-SA and CC-BY-NC-SA) and non-software license used

### ISSUE THREAD

**Issue by Erudition** [rogerlinndesign/linnstrument-firmware#53]
The licensing of the source code is a bit unclear.

The Linnstrument license document contains a copy of the CC-BY-SA license.
Then each file of the source code is prepended with the license header that says the same:
https://github.com/rogerlinndesign/linnstrument-firmware/blob/ab580e0a6a186e8d905faad787248dc2b5bc6137/linnstrument-firmware.ino#L9
...with a link to the CC-BY-SA license.
https://github.com/rogerlinndesign/linnstrument-firmware/blob/ab580e0a6a186e8d905faad787248dc2b5bc6137/linnstrument-firmware.ino#L10
However, in the primary .ino file it then goes on to say:

```
You are free:
1) to Share — to copy, distribute and transmit the work
2) to Remix — to adapt the work
Under the following conditions:
[..]
2) Noncommercial — You may not use this work for commercial purposes.
```

These stipulations are not the CC-BY-SA license -- the added noncommercial clause is incompatible with the CC-BY-SA. Another license, the CC-BY-**NC**-SA license, is the one that adds this restriction, but that's not what's in the LICENSE file. (The NC license is also [not](https://www.gnu.org/licenses/license-list#CC-BY-NC) Free/Libre/Open, unlike the CC-BY-SA.) 

In addition, the same header finishes with:

https://github.com/rogerlinndesign/linnstrument-firmware/blob/ab580e0a6a186e8d905faad787248dc2b5bc6137/linnstrument-firmware.ino#L34
```
Notice — For any reuse or distribution, you must make clear to others the license terms of this work.
The best way to do this is with a link to http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US
```
That link is to the aforementioned CC-BY-**NC**-SA license, which would explain the additional clause, however it contradicts the (more authoratative) claim 24 lines prior, stating that CC-BY-SA is the license. This also contradicts the LICENSE file which is a copy of CC-BY-SA.

Every other source code file, however, has a header that only claims CC-BY-SA.
https://github.com/rogerlinndesign/linnstrument-firmware/blob/ab580e0a6a186e8d905faad787248dc2b5bc6137/ls_playbook.ino#L2

So it seems that CC-BY-SA is the real license, so the second half of the header in linnstrument-firmware.ino should be removed. (If CC-BY-NC-SA is actually the real license, many other things should be changed, including claims to an open source license)

# CC licenses are not for software
The other problem is that CC licenses are not made for software anyway. [Here's the Creative Commons website saying not to use it for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), and the publishers of FLO licenses, the OSI and FSF, say the same. A good approximation of the CC-BY-SA that is meant for software is [the GPL](https://www.gnu.org/licenses/license-list#GPLCompatibleLicenses).

**Comment by wolftune** [comment]
Note: CC-BY-SA is explicitly one-way compatible with GPL. So, switching everything to GPLv3 would be easy to do and is the correct decision here. See https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/ and the links there for wiki articles with details and analysis.

The short point is: CC licenses do not require source code availability along with the sharing. Thus, they are not effective for keeping the software free. The GPL is the best and correct license for Linnstrument firmware, and it does what CC BY-SA is trying to do but more effectively and more appropriately for software.

**Comment by gbevin** [comment]
Thanks for reminding of as this, the CC license was initially chosen since that's what Arduino was also using. Afterwards CC published the statement about not using it for software. We decided to move to the more permissive Apache-2.0 license, that has now been applied to the code.
